---
- name: Pull docker image of calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull dutta78/spe_project
    - name: running container
      shell: docker run -it -d 8000:8000 dutta78/spe_project /bin/bash
